# Tuning: FD002 / FD004, XGBoost and LSTM

Exploration only, nothing here is load-bearing on its own (see CLAUDE.md) -- the winning hyperparameters found here get copied into `src/models.py`'s `XGB_HYPERPARAMS` / `LSTM_HYPERPARAMS` dicts, which *are* load-bearing.

**Why FD002/FD004 only:** both are above their published benchmark RMSE range for both model families (measured in `docs/Log.md`, 2026-09-10 session), while FD001/FD003 already land inside range with zero tuning. FD002/FD004 also have a genuinely harder learning problem -- 6 mixed operating regimes and (for FD004) 2 fault modes, vs. FD001/FD003's single condition -- so each gets tuned independently rather than searching for one hyperparameter setting shared across all four (decision discussed and confirmed: each dataset already trains a separate model instance, tuning just extends that to hyperparameters too).

**Selection metric:** GroupKFold CV RMSE for XGBoost (matches how every other XGBoost number in this project is validated, and `N_SPLITS=7` was just confirmed trustworthy in `eda_cv_folds.ipynb`), and validation-split RMSE for the LSTM (matches how the LSTM is already validated in `models.py` -- a single unit-based holdout, not k-fold, per the standing neural-net validation decision). Test-set RMSE at the final cycle is only computed *after* a winner is picked, never used to pick it -- picking hyperparameters by looking at the test set would be leakage of a different kind than the unit-split kind, but leakage all the same.

In [1]:
import os
import sys

if os.path.basename(os.getcwd()) == "notebooks":
    os.chdir("..")
sys.path.insert(0, os.getcwd())

import numpy as np
import pandas as pd
from sklearn.model_selection import GroupKFold, RandomizedSearchCV

from src.features import add_rolling_features, add_rul_targets, add_savgol_features, find_constant_sensors
from src.load import SENSOR_COLS, load_train
from src.models import build_feature_cols, fit_lstm_scaler, make_xgb_model, train_lstm
from src.regimes import fit_regimes
from src.scoring import N_SPLITS, group_kfold_cv, rmse

SEED = 42
TUNE_DATASETS = ["FD002", "FD004"]


def build_train_features(dataset: str):
    train = load_train(dataset)
    train_norm, _ = fit_regimes(train)
    constant_sensors = find_constant_sensors(train_norm)
    varying_sensors = [s for s in SENSOR_COLS if s not in constant_sensors]
    train_feat = add_rolling_features(train_norm, varying_sensors)
    train_feat = add_savgol_features(train_feat, varying_sensors)
    train_feat = add_rul_targets(train_feat)
    feature_cols = build_feature_cols(varying_sensors)
    return train_feat, feature_cols


train_features = {ds: build_train_features(ds) for ds in TUNE_DATASETS}

## XGBoost: RandomizedSearchCV over the standard tree hyperparameters

**Question:** does searching over tree depth / learning rate / tree count / subsampling find something meaningfully better than XGBoost's plain defaults (what FD002/FD004 currently use)?

Grid ranges are the standard tuning ranges for gradient-boosted trees, not derived from EDA on this data specifically:
- `n_estimators`: [100, 200, 300, 500] -- more trees, more capacity, more compute
- `max_depth`: [3, 4, 5, 6, 8] -- default is 6; both shallower (less overfitting) and deeper (more capacity, since FD002/FD004 have more rows and more structure to fit) are worth trying
- `learning_rate`: [0.01, 0.03, 0.05, 0.1, 0.2] -- default is 0.3; smaller steps with more trees is the standard pairing
- `subsample` / `colsample_bytree`: [0.6, 0.8, 1.0] each -- row/column subsampling, a standard regularizer against overfitting
- `min_child_weight`: [1, 3, 5, 7] -- default is 1; higher values require more evidence before a tree splits further

`RandomizedSearchCV` samples 40 combinations from this space (seed=42, so the sample itself is reproducible) rather than the ~2,800 a full grid would need -- 40 is enough to cover the space reasonably given XGBoost trains fast, without an exhaustive search that isn't needed here.

In [2]:
XGB_PARAM_GRID = {
    "n_estimators": [100, 200, 300, 500],
    "max_depth": [3, 4, 5, 6, 8],
    "learning_rate": [0.01, 0.03, 0.05, 0.1, 0.2],
    "subsample": [0.6, 0.8, 1.0],
    "colsample_bytree": [0.6, 0.8, 1.0],
    "min_child_weight": [1, 3, 5, 7],
}

xgb_search_results = {}
xgb_rows = []
for dataset in TUNE_DATASETS:
    train_feat, feature_cols = train_features[dataset]

    default_cv_rmses = group_kfold_cv(make_xgb_model, train_feat, feature_cols, "rul_capped", n_splits=N_SPLITS)
    default_mean = float(np.mean(default_cv_rmses))

    search = RandomizedSearchCV(
        estimator=make_xgb_model(),
        param_distributions=XGB_PARAM_GRID,
        n_iter=40,
        cv=GroupKFold(n_splits=N_SPLITS),
        scoring="neg_root_mean_squared_error",
        random_state=SEED,
        n_jobs=-1,
    )
    search.fit(train_feat[feature_cols], train_feat["rul_capped"], groups=train_feat["unit"])

    xgb_search_results[dataset] = search
    xgb_rows.append({
        "dataset": dataset,
        "default_cv_rmse": default_mean,
        "best_cv_rmse": -search.best_score_,
        "improvement": default_mean - (-search.best_score_),
        "best_params": search.best_params_,
    })

xgb_tuning_results = pd.DataFrame(xgb_rows)
xgb_tuning_results

,dataset,default_cv_rmse,best_cv_rmse,improvement,best_params
0,FD002,15.834899,14.894821,0.940078,"{'subsample': 0.6, 'n_estimators': 500, 'min_c..."
1,FD004,15.430032,14.652904,0.777128,"{'subsample': 0.8, 'n_estimators': 300, 'min_c..."

**XGBoost finding:** placeholder -- filled in after running the search above.

## LSTM: 4 reasoned variants vs. the current baseline

**Question:** does any of a small number of specific, explainable architecture changes beat the current LSTM (64 units, 1 layer, dropout 0.2, 30-cycle window) on validation RMSE?

Each variant is a genuine hypothesis about *why* FD002/FD004 specifically underperform, not a blind grid:
- **units=128**: 6 mixed operating regimes is a harder pattern than FD001/FD003's single condition -- maybe the model needs more capacity to represent it.
- **2 stacked layers (64 units each)**: lets the network build a regime-level representation in the first layer before a degradation-level one in the second, instead of learning both at once.
- **window=20**: FD002 test data has 6 units shorter than the current 30-cycle training window (minimum 21 cycles), and FD004 has 11 (minimum 19) -- see `docs/dataset-reference.md`. Training exclusively on 30-cycle windows means the model has never seen anything resembling what it faces on those short units at test time. A 20-cycle window closes most of that gap (fully for FD002, partially for FD004).
- **bidirectional**: added after a literature check specifically for this dataset (see `docs/Log.md`) turned up a published bidirectional-LSTM result beating plain and CNN-LSTM architectures on FD002. Reads each window back-to-front as well as front-to-back -- not future-peeking, since by the time the model sees a window it's already a fixed, fully-known slice of the past. Mechanically different from the other three (which all just add more of the same one-directional capacity), so it isn't a repeat of an already-disproven idea.

Selection metric is validation RMSE (the best epoch's `val_rmse`, i.e. what early stopping already tracks) -- not the test set, per the note above.

In [3]:
LSTM_VARIANTS = {
    "baseline (units=64, 1 layer, window=30)": {},
    "units=128": {"units": 128},
    "2 stacked layers (units=64 each)": {"num_layers": 2},
    "window=20": {"window": 20},
    "bidirectional": {"bidirectional": True},
}

lstm_models = {}
lstm_rows = []
for dataset in TUNE_DATASETS:
    train_feat, feature_cols = train_features[dataset]
    lstm_scaler = fit_lstm_scaler(train_feat, feature_cols)
    for variant_name, overrides in LSTM_VARIANTS.items():
        model = train_lstm(train_feat, feature_cols, lstm_scaler, **overrides)
        best_val_rmse = float(min(model.history.history["val_rmse"]))
        lstm_models[(dataset, variant_name)] = model
        lstm_rows.append({"dataset": dataset, "variant": variant_name, "val_rmse": best_val_rmse})

lstm_tuning_results = pd.DataFrame(lstm_rows)
lstm_tuning_results

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Epoch 1/50

585/585 - 7s - 11ms/step - loss: 4597.5488 - rmse: 67.8052 - val_loss: 2565.6333 - val_rmse: 50.6521

Epoch 2/50

585/585 - 5s - 8ms/step - loss: 1858.2715 - rmse: 43.1077 - val_loss: 1063.9550 - val_rmse: 32.6183

Epoch 3/50

585/585 - 5s - 8ms/step - loss: 788.5012 - rmse: 28.0803 - val_loss: 473.6191 - val_rmse: 21.7628

Epoch 4/50

585/585 - 5s - 8ms/step - loss: 371.3343 - rmse: 19.2700 - val_loss: 269.2746 - val_rmse: 16.4096

Epoch 5/50

585/585 - 5s - 9ms/step - loss: 216.2557 - rmse: 14.7056 - val_loss: 214.9658 - val_rmse: 14.6617

Epoch 6/50

585/585 - 5s - 9ms/step - loss: 151.5504 - rmse: 12.3106 - val_loss: 215.6285 - val_rmse: 14.6843

Epoch 7/50

585/585 - 11s - 18ms/step - loss: 122.3007 - rmse: 11.0590 - val_loss: 234.0123 - val_rmse: 15.2975

Epoch 8/50

585/585 - 5s - 9ms/step - loss: 105.7377 - rmse: 10.2829 - val_loss: 229.4673 - val_rmse: 15.1482

Epoch 9/50

585/585 - 6s - 10ms/step - loss: 91.3484 - rmse: 9.5576 - val_loss: 241.3091 - val_rmse: 15.5341

Epoch 10/50

585/585 - 5s - 9ms/step - loss: 79.6334 - rmse: 8.9238 - val_loss: 231.8119 - val_rmse: 15.2254

Epoch 1/50

585/585 - 12s - 20ms/step - loss: 3196.0601 - rmse: 56.5337 - val_loss: 1003.6273 - val_rmse: 31.6801

Epoch 2/50

585/585 - 9s - 16ms/step - loss: 571.2373 - rmse: 23.9006 - val_loss: 268.1818 - val_rmse: 16.3763

Epoch 3/50

585/585 - 9s - 16ms/step - loss: 215.5820 - rmse: 14.6827 - val_loss: 192.7112 - val_rmse: 13.8820

Epoch 4/50

585/585 - 9s - 16ms/step - loss: 143.9196 - rmse: 11.9966 - val_loss: 176.8839 - val_rmse: 13.2998

Epoch 5/50

585/585 - 9s - 16ms/step - loss: 110.5497 - rmse: 10.5143 - val_loss: 204.8627 - val_rmse: 14.3130

Epoch 6/50

585/585 - 9s - 16ms/step - loss: 86.4792 - rmse: 9.2994 - val_loss: 203.9325 - val_rmse: 14.2805

Epoch 7/50

585/585 - 10s - 17ms/step - loss: 65.4323 - rmse: 8.0890 - val_loss: 221.8820 - val_rmse: 14.8957

Epoch 8/50

585/585 - 10s - 16ms/step - loss: 53.2513 - rmse: 7.2973 - val_loss: 230.4537 - val_rmse: 15.1807

Epoch 9/50

585/585 - 11s - 19ms/step - loss: 44.7051 - rmse: 6.6862 - val_loss: 218.0038 - val_rmse: 14.7650

Epoch 1/50

585/585 - 13s - 21ms/step - loss: 4583.6104 - rmse: 67.7024 - val_loss: 2596.9370 - val_rmse: 50.9602

Epoch 2/50

585/585 - 9s - 16ms/step - loss: 1873.8904 - rmse: 43.2885 - val_loss: 1057.2125 - val_rmse: 32.5148

Epoch 3/50

585/585 - 9s - 16ms/step - loss: 772.4280 - rmse: 27.7926 - val_loss: 478.2499 - val_rmse: 21.8689

Epoch 4/50

585/585 - 10s - 17ms/step - loss: 334.3571 - rmse: 18.2854 - val_loss: 279.6483 - val_rmse: 16.7227

Epoch 5/50

585/585 - 10s - 17ms/step - loss: 161.8363 - rmse: 12.7215 - val_loss: 214.1516 - val_rmse: 14.6339

Epoch 6/50

585/585 - 9s - 16ms/step - loss: 97.0018 - rmse: 9.8489 - val_loss: 218.8033 - val_rmse: 14.7920

Epoch 7/50

585/585 - 9s - 16ms/step - loss: 69.6775 - rmse: 8.3473 - val_loss: 216.5663 - val_rmse: 14.7162

Epoch 8/50

585/585 - 9s - 16ms/step - loss: 58.1073 - rmse: 7.6228 - val_loss: 229.7133 - val_rmse: 15.1563

Epoch 9/50

585/585 - 9s - 16ms/step - loss: 52.3747 - rmse: 7.2370 - val_loss: 233.0125 - val_rmse: 15.2647

Epoch 10/50

585/585 - 10s - 16ms/step - loss: 48.6695 - rmse: 6.9764 - val_loss: 236.2178 - val_rmse: 15.3694

Epoch 1/50

618/618 - 5s - 8ms/step - loss: 4744.9370 - rmse: 68.8835 - val_loss: 2615.4966 - val_rmse: 51.1419

Epoch 2/50

618/618 - 4s - 6ms/step - loss: 1837.9200 - rmse: 42.8710 - val_loss: 1032.0140 - val_rmse: 32.1250

Epoch 3/50

618/618 - 4s - 6ms/step - loss: 749.4277 - rmse: 27.3757 - val_loss: 457.9697 - val_rmse: 21.4002

Epoch 4/50

618/618 - 4s - 6ms/step - loss: 352.1711 - rmse: 18.7662 - val_loss: 289.6127 - val_rmse: 17.0180

Epoch 5/50

618/618 - 4s - 6ms/step - loss: 215.4892 - rmse: 14.6796 - val_loss: 252.2838 - val_rmse: 15.8834

Epoch 6/50

618/618 - 3s - 6ms/step - loss: 160.8004 - rmse: 12.6807 - val_loss: 246.2074 - val_rmse: 15.6910

Epoch 7/50

618/618 - 4s - 6ms/step - loss: 135.5818 - rmse: 11.6440 - val_loss: 260.7320 - val_rmse: 16.1472

Epoch 8/50

618/618 - 4s - 6ms/step - loss: 113.9859 - rmse: 10.6764 - val_loss: 253.8260 - val_rmse: 15.9319

Epoch 9/50

618/618 - 4s - 6ms/step - loss: 101.7104 - rmse: 10.0852 - val_loss: 238.3908 - val_rmse: 15.4399

Epoch 10/50

618/618 - 3s - 6ms/step - loss: 90.7372 - rmse: 9.5256 - val_loss: 248.4428 - val_rmse: 15.7621

Epoch 11/50

618/618 - 4s - 6ms/step - loss: 81.6819 - rmse: 9.0378 - val_loss: 259.1550 - val_rmse: 16.0983

Epoch 12/50

618/618 - 3s - 6ms/step - loss: 75.9646 - rmse: 8.7158 - val_loss: 269.0567 - val_rmse: 16.4029

Epoch 13/50

618/618 - 4s - 6ms/step - loss: 73.4419 - rmse: 8.5698 - val_loss: 259.8048 - val_rmse: 16.1185

Epoch 14/50

618/618 - 4s - 6ms/step - loss: 67.4810 - rmse: 8.2147 - val_loss: 270.8743 - val_rmse: 16.4583

Epoch 1/50

585/585 - 8s - 14ms/step - loss: 3007.6775 - rmse: 54.8423 - val_loss: 968.2892 - val_rmse: 31.1173

Epoch 2/50

585/585 - 6s - 10ms/step - loss: 548.6747 - rmse: 23.4238 - val_loss: 298.8422 - val_rmse: 17.2871

Epoch 3/50

585/585 - 6s - 10ms/step - loss: 211.6184 - rmse: 14.5471 - val_loss: 238.6104 - val_rmse: 15.4470

Epoch 4/50

585/585 - 6s - 10ms/step - loss: 134.8563 - rmse: 11.6128 - val_loss: 248.8544 - val_rmse: 15.7751

Epoch 5/50

585/585 - 6s - 10ms/step - loss: 98.3846 - rmse: 9.9189 - val_loss: 232.0878 - val_rmse: 15.2344

Epoch 6/50

585/585 - 6s - 10ms/step - loss: 73.2341 - rmse: 8.5577 - val_loss: 261.1393 - val_rmse: 16.1598

Epoch 7/50

585/585 - 6s - 10ms/step - loss: 59.5761 - rmse: 7.7186 - val_loss: 267.2430 - val_rmse: 16.3476

Epoch 8/50

585/585 - 6s - 10ms/step - loss: 49.1024 - rmse: 7.0073 - val_loss: 261.9122 - val_rmse: 16.1837

Epoch 9/50

585/585 - 6s - 10ms/step - loss: 43.0242 - rmse: 6.5593 - val_loss: 269.2523 - val_rmse: 16.4089

Epoch 10/50

585/585 - 6s - 10ms/step - loss: 38.9338 - rmse: 6.2397 - val_loss: 275.2676 - val_rmse: 16.5912

Epoch 1/50

681/681 - 7s - 10ms/step - loss: 5178.4360 - rmse: 71.9613 - val_loss: 2894.3494 - val_rmse: 53.7992

Epoch 2/50

681/681 - 5s - 8ms/step - loss: 1884.5919 - rmse: 43.4119 - val_loss: 1076.1715 - val_rmse: 32.8051

Epoch 3/50

681/681 - 5s - 8ms/step - loss: 681.3482 - rmse: 26.1026 - val_loss: 471.2074 - val_rmse: 21.7073

Epoch 4/50

681/681 - 5s - 8ms/step - loss: 267.0599 - rmse: 16.3420 - val_loss: 294.6892 - val_rmse: 17.1665

Epoch 5/50

681/681 - 5s - 8ms/step - loss: 142.1532 - rmse: 11.9228 - val_loss: 255.4387 - val_rmse: 15.9824

Epoch 6/50

681/681 - 5s - 8ms/step - loss: 102.5054 - rmse: 10.1245 - val_loss: 260.8150 - val_rmse: 16.1498

Epoch 7/50

681/681 - 6s - 9ms/step - loss: 87.9298 - rmse: 9.3771 - val_loss: 264.5477 - val_rmse: 16.2649

Epoch 8/50

681/681 - 6s - 8ms/step - loss: 82.0852 - rmse: 9.0601 - val_loss: 280.7189 - val_rmse: 16.7547

Epoch 9/50

681/681 - 6s - 9ms/step - loss: 74.4687 - rmse: 8.6295 - val_loss: 285.4042 - val_rmse: 16.8939

Epoch 10/50

681/681 - 5s - 8ms/step - loss: 68.7969 - rmse: 8.2944 - val_loss: 292.2742 - val_rmse: 17.0960

Epoch 1/50

681/681 - 12s - 18ms/step - loss: 3297.1912 - rmse: 57.4212 - val_loss: 1028.6046 - val_rmse: 32.0719

Epoch 2/50

681/681 - 11s - 16ms/step - loss: 479.6345 - rmse: 21.9006 - val_loss: 346.2380 - val_rmse: 18.6075

Epoch 3/50

681/681 - 11s - 17ms/step - loss: 165.2080 - rmse: 12.8533 - val_loss: 284.3824 - val_rmse: 16.8636

Epoch 4/50

681/681 - 11s - 16ms/step - loss: 109.7200 - rmse: 10.4747 - val_loss: 271.2154 - val_rmse: 16.4686

Epoch 5/50

681/681 - 11s - 16ms/step - loss: 83.1251 - rmse: 9.1173 - val_loss: 324.4220 - val_rmse: 18.0117

Epoch 6/50

681/681 - 11s - 16ms/step - loss: 67.2919 - rmse: 8.2032 - val_loss: 305.2108 - val_rmse: 17.4703

Epoch 7/50

681/681 - 20s - 30ms/step - loss: 54.7438 - rmse: 7.3989 - val_loss: 302.5927 - val_rmse: 17.3952

Epoch 8/50

681/681 - 12s - 17ms/step - loss: 48.4231 - rmse: 6.9587 - val_loss: 314.6935 - val_rmse: 17.7396

Epoch 9/50

681/681 - 16s - 24ms/step - loss: 43.9843 - rmse: 6.6321 - val_loss: 339.0253 - val_rmse: 18.4126

Epoch 1/50

681/681 - 18s - 27ms/step - loss: 5104.2305 - rmse: 71.4439 - val_loss: 2886.5349 - val_rmse: 53.7265

Epoch 2/50

681/681 - 16s - 23ms/step - loss: 1864.5306 - rmse: 43.1802 - val_loss: 1056.6008 - val_rmse: 32.5054

Epoch 3/50

681/681 - 15s - 23ms/step - loss: 642.1927 - rmse: 25.3415 - val_loss: 467.4779 - val_rmse: 21.6212

Epoch 4/50

681/681 - 15s - 22ms/step - loss: 225.6830 - rmse: 15.0228 - val_loss: 354.0410 - val_rmse: 18.8160

Epoch 5/50

681/681 - 15s - 23ms/step - loss: 100.4735 - rmse: 10.0236 - val_loss: 358.4814 - val_rmse: 18.9336

Epoch 6/50

681/681 - 16s - 23ms/step - loss: 67.4566 - rmse: 8.2132 - val_loss: 309.0463 - val_rmse: 17.5797

Epoch 7/50

681/681 - 13s - 20ms/step - loss: 55.2341 - rmse: 7.4320 - val_loss: 334.9688 - val_rmse: 18.3022

Epoch 8/50

681/681 - 11s - 16ms/step - loss: 51.4581 - rmse: 7.1734 - val_loss: 310.7168 - val_rmse: 17.6272

Epoch 9/50

681/681 - 12s - 17ms/step - loss: 48.5646 - rmse: 6.9688 - val_loss: 324.3641 - val_rmse: 18.0101

Epoch 10/50

681/681 - 12s - 17ms/step - loss: 45.8803 - rmse: 6.7735 - val_loss: 355.9292 - val_rmse: 18.8661

Epoch 11/50

681/681 - 12s - 17ms/step - loss: 46.2889 - rmse: 6.8036 - val_loss: 341.3336 - val_rmse: 18.4752

Epoch 1/50

712/712 - 8s - 11ms/step - loss: 5222.9282 - rmse: 72.2698 - val_loss: 2875.4834 - val_rmse: 53.6235

Epoch 2/50

712/712 - 5s - 7ms/step - loss: 1842.2877 - rmse: 42.9219 - val_loss: 1030.9784 - val_rmse: 32.1089

Epoch 3/50

712/712 - 6s - 8ms/step - loss: 648.3702 - rmse: 25.4631 - val_loss: 437.6993 - val_rmse: 20.9213

Epoch 4/50

712/712 - 4s - 6ms/step - loss: 271.5011 - rmse: 16.4773 - val_loss: 295.9773 - val_rmse: 17.2040

Epoch 5/50

712/712 - 5s - 8ms/step - loss: 164.2370 - rmse: 12.8155 - val_loss: 278.0206 - val_rmse: 16.6740

Epoch 6/50

712/712 - 4s - 6ms/step - loss: 130.4810 - rmse: 11.4228 - val_loss: 287.3778 - val_rmse: 16.9522

Epoch 7/50

712/712 - 4s - 6ms/step - loss: 111.5029 - rmse: 10.5595 - val_loss: 294.2594 - val_rmse: 17.1540

Epoch 8/50

712/712 - 4s - 6ms/step - loss: 98.2026 - rmse: 9.9097 - val_loss: 311.5184 - val_rmse: 17.6499

Epoch 9/50

712/712 - 4s - 6ms/step - loss: 90.8880 - rmse: 9.5335 - val_loss: 304.3844 - val_rmse: 17.4466

Epoch 10/50

712/712 - 4s - 6ms/step - loss: 83.1744 - rmse: 9.1200 - val_loss: 300.1770 - val_rmse: 17.3256

Epoch 1/50

681/681 - 9s - 13ms/step - loss: 3171.4395 - rmse: 56.3155 - val_loss: 956.3195 - val_rmse: 30.9244

Epoch 2/50

681/681 - 7s - 10ms/step - loss: 427.2548 - rmse: 20.6701 - val_loss: 330.1890 - val_rmse: 18.1711

Epoch 3/50

681/681 - 7s - 10ms/step - loss: 139.4685 - rmse: 11.8097 - val_loss: 282.3019 - val_rmse: 16.8018

Epoch 4/50

681/681 - 7s - 10ms/step - loss: 92.8235 - rmse: 9.6345 - val_loss: 288.1723 - val_rmse: 16.9756

Epoch 5/50

681/681 - 7s - 10ms/step - loss: 70.2869 - rmse: 8.3837 - val_loss: 281.0866 - val_rmse: 16.7656

Epoch 6/50

681/681 - 7s - 10ms/step - loss: 60.8785 - rmse: 7.8025 - val_loss: 299.6056 - val_rmse: 17.3091

Epoch 7/50

681/681 - 7s - 10ms/step - loss: 50.8875 - rmse: 7.1335 - val_loss: 310.0652 - val_rmse: 17.6087

Epoch 8/50

681/681 - 7s - 10ms/step - loss: 47.0006 - rmse: 6.8557 - val_loss: 303.7914 - val_rmse: 17.4296

Epoch 9/50

681/681 - 7s - 10ms/step - loss: 43.6788 - rmse: 6.6090 - val_loss: 305.4193 - val_rmse: 17.4762

Epoch 10/50

681/681 - 10s - 15ms/step - loss: 39.1896 - rmse: 6.2602 - val_loss: 318.3306 - val_rmse: 17.8418

  dataset                                  variant   val_rmse
0   FD002  baseline (units=64, 1 layer, window=30)  14.661711
1   FD002                                units=128  13.299772
2   FD002         2 stacked layers (units=64 each)  14.633920
3   FD002                                window=20  15.439909
4   FD002                            bidirectional  15.234427
5   FD004  baseline (units=64, 1 layer, window=30)  15.982450
6   FD004                                units=128  16.468618
7   FD004         2 stacked layers (units=64 each)  17.579714
8   FD004                                window=20  16.673950
9   FD004                            bidirectional  16.765636

In [4]:
print("val_rmse by dataset x variant:")
print(lstm_tuning_results.pivot(index="variant", columns="dataset", values="val_rmse").round(2))
print()

for dataset in TUNE_DATASETS:
    subset = lstm_tuning_results[lstm_tuning_results["dataset"] == dataset]
    winner = subset.loc[subset["val_rmse"].idxmin(), "variant"]
    print(f"{dataset}: best variant = {winner} (val_rmse={subset['val_rmse'].min():.2f})")

val_rmse by dataset x variant:
dataset                                  FD002  FD004
variant
2 stacked layers (units=64 each)         14.63  17.58
baseline (units=64, 1 layer, window=30)  14.66  15.98
bidirectional                            15.23  16.77
units=128                                13.30  16.47
window=20                                15.44  16.67

FD002: best variant = units=128 (val_rmse=13.30)
FD004: best variant = baseline (units=64, 1 layer, window=30) (val_rmse=15.98)

**LSTM finding:** placeholder -- filled in after running the variants above.

## Test-set check (informational only -- not used to pick anything above)

Evaluates the winning XGBoost and LSTM configuration per dataset at the final test cycle, to see the actual required-output-shaped number and compare against the current (untuned) test RMSEs on record: FD002 xgboost=28.73/lstm=27.86, FD004 xgboost=28.82/lstm=26.53 (`docs/Log.md`, 2026-09-12).

In [5]:
from src.load import load_rul, load_test
from src.regimes import apply_regimes
from src.scoring import evaluate_at_final_cycle, evaluate_sequence_model_at_final_cycle

for dataset in TUNE_DATASETS:
    train_feat, feature_cols = train_features[dataset]
    test = load_test(dataset)
    rul_true = load_rul(dataset)

    _, fitted = fit_regimes(load_train(dataset))
    test_norm = apply_regimes(test, fitted)
    constant_sensors = find_constant_sensors(fit_regimes(load_train(dataset))[0])
    varying_sensors = [s for s in SENSOR_COLS if s not in constant_sensors]
    test_feat = add_rolling_features(test_norm, varying_sensors)
    test_feat = add_savgol_features(test_feat, varying_sensors)

    xgb_best_model = xgb_search_results[dataset].best_estimator_
    xgb_test = evaluate_at_final_cycle(xgb_best_model, test_feat, feature_cols, rul_true)
    print(f"{dataset} xgboost tuned: test rmse={xgb_test['rmse']:.2f} (was {'28.73' if dataset=='FD002' else '28.82'})")

    subset = lstm_tuning_results[lstm_tuning_results["dataset"] == dataset]
    winner = subset.loc[subset["val_rmse"].idxmin(), "variant"]
    lstm_best_model = lstm_models[(dataset, winner)]
    lstm_scaler = fit_lstm_scaler(train_feat, feature_cols)
    test_feat_scaled = test_feat.copy()
    test_feat_scaled[feature_cols] = lstm_scaler.transform(test_feat[feature_cols])
    window_used = LSTM_VARIANTS[winner].get("window", 30)
    lstm_test = evaluate_sequence_model_at_final_cycle(lstm_best_model, test_feat_scaled, feature_cols, rul_true, window_used)
    print(f"{dataset} lstm tuned ({winner}): test rmse={lstm_test['rmse']:.2f} (was {'27.86' if dataset=='FD002' else '26.53'})")

FD002 xgboost tuned: test rmse=27.71 (was 28.73)

FD002 lstm tuned (units=128): test rmse=26.10 (was 27.86)

FD004 xgboost tuned: test rmse=28.24 (was 28.82)

FD004 lstm tuned (baseline (units=64, 1 layer, window=30)): test rmse=27.72 (was 26.53)

**Overall finding:** placeholder -- filled in after running everything above. Whatever wins gets copied into `src/models.py`'s `XGB_HYPERPARAMS` / `LSTM_HYPERPARAMS` dicts for FD002/FD004, and `src/pipeline.py` gets updated to use them.